HW2/website/tasktracker/urls.py
from django.urls import path
from . import views

app_name = 'tasktracker'  # creates a namespace for this application


urlpatterns = [
    # ex: /tasktracker/
    path('', views.index, name='index'),
    # ex: /tasktracker/add/
    path('add/', views.add, name='add'),
    # ex: /tasktracker/delete/5
    path('delete/<int:pk>/', views.delete, name='delete'),
]

HW2/website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # delegates to the urls.py inside tasktracker app (folder)
    path('tasktracker/', include('tasktracker.urls')),
    # admin interface (not relevant for this assignment)
    path('admin/', admin.site.urls),
    # login interface provided by a built-in module
    path('accounts/', include('django.contrib.auth.urls')),
]

HW2/website/tasktracker/models.py
from django.db import models
from django.contrib.auth.models import User

# The status for a task
TASK_STATUS_CHOICES = [
    ('C', 'Completed'),
    ('I', 'In progress'),
    ('N', 'Not started yet'),
]

# Specifies the Task table in the database
class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    due_date = models.DateField()
    status =  models.CharField(max_length=1, choices=TASK_STATUS_CHOICES) 
    def __str__(self):
    	return f"Task #{self.id}: {self.title}" 

HW2/website/tasktracker/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from .models import Task
from django.db import connection
from django.core.exceptions import ValidationError


# View functions
def index(request):
	# checks whether user is authenticated
	if request.user.is_authenticated:
		# gets all tasks from the database
		task_list = Task.objects.filter(user=request.user) 
		# creates a dictionary to pass this list to the template file
		template_data = {'tasks': task_list}
		# renders the web page
		return render(request, 'index.html', template_data)
	else:
		return HttpResponseRedirect(reverse(f'login'))

# Adds a new task and redirect it back to index page
def add(request):
	if request.user.is_authenticated:
		# if the form was submitted
		if request.POST:
			title = request.POST['title']
			due_date = request.POST['due_date']
			status = request.POST['status']
			task = Task(user = request.user, title = title, due_date = due_date, status = status)
			# does input validation (full_clean() throws an exception if validation fails)
			try:
				task.full_clean() 
				# if no exception was thrown, form was validated
				# we proceed to save the task in the database
				with connection.cursor() as cursor:
					cursor.executescript(f"INSERT INTO tasktracker_task(user_id, status, due_date, title) VALUES ({request.user.id},'{status}', '{due_date}', '{title}')")				
			except ValidationError as e:
				# renders the web page again with an error message
				return render(request, 'add.html', {"errors": e.message_dict})
				
			return HttpResponseRedirect(reverse(f'tasktracker:index'))
		else:
			# renders the web page
			return render(request, 'add.html')
	else:
		return HttpResponseRedirect(reverse(f'login'))


# Deletes a task (based on its primary key) and redirect it back to index page
def delete(request, pk):
	# uses ORM to delete the task
	task = Task.objects.get(id = pk)
	task.delete()
	# redirects user to index page
	return HttpResponseRedirect(reverse(f'tasktracker:index'))

HW2/website/tasktracker/templates/add.html
{% extends "base_generic.html" %}

{% block content %}      
	<div class="col-lg-10 p-3 mx-auto border">
   <h1>Add new Task</h1>

   {%if errors %}
   	<div class="alert alert-danger p-1" role="alert">
      	{% for key, item_errors in errors.items %}
      		{{key}}: 
      		<ul>
      			{% for error in item_errors %}<li>{{error}}</li>{% endfor %}
      		</ul>
      	{% endfor %}
   	</div>
   {% endif %}
   <form action="/tasktracker/add/" method = "POST">
      {% csrf_token %}
      <div class="mb-3 row">
         <label for="title" class="col-sm-2 col-form-label">Task title:</label>
         <div class="col-sm-10">
            <input type="text" class="form-control" id="title" name="title" value="{{request.POST.title}}">
         </div>
      </div>
      <div class="mb-3 row">
         <label for="due_date" class="col-sm-2 col-form-label">Due date:</label>
         <div class="col-sm-10">
               <input type="text" class="form-control" id="due_date" name="due_date" value="{{request.POST.due_date}}">
         </div>
      </div>
      <div class="mb-3 row">
         <label for="due_date" class="col-sm-2 col-form-label">Due date:</label>
         <div class="col-sm-10">
            <select name="status" required="" id="id_status">
              <option value="C" {% if request.POST.status == 'C' %}selected{% endif %}>Completed</option>
              <option value="I" {% if request.POST.status == 'I' %}selected{% endif %}>In progress</option>
              <option value="N" {% if request.POST.status == 'N' %}selected{% endif %}>Not started yet</option>
            </select>
         </div>
      </div>
      <input class="btn btn-success" type="submit" value="Add Task">
   </form>
</div>
{% endblock %}

HW2/website/tasktracker/templates/base_generic.html
<!DOCTYPE html>
<html data-lt-installed="true" lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="Joanna Cecilia da Silva Santos (based on Starter Template)">
      <title>Task Track Management App</title>
      <!-- Bootstrap core CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">      
   </head>
   <body>
   		<!-- Display navbar in the template only for authenticated pages -->
   		{% if request.user.is_authenticated %}
   		<nav class="navbar navbar-expand-md navbar-light bg-info">
		    <div class="container-fluid">
		        <a class="navbar-brand abs" href="{% url 'tasktracker:index' %}">Home</a>
		        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
		            <span class="navbar-toggler-icon"></span>
		        </button>
		        <div class="navbar-collapse collapse" id="collapseNavbar">
		            <ul class="navbar-nav ms-auto">
		            	<li class="nav-item">
		            		<p class="m-0 p-2">Signed in as <b>{{request.user}}</b></p>
		            	</li>
		                <li class="nav-item">
		                    <a class="nav-link" href="{% url 'logout' %}?next={% url 'login' %}" data-bs-target="#myModal" data-bs-toggle="modal">Logout</a>
		                </li>
		            </ul>
		        </div>
		    </div>
		</nav>
		{%endif%}
		<!-- The block below can be extended by children templates -->
   		{% block content %}{% endblock%}         	
   </body>
</html>

HW2/website/tasktracker/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="col-lg-10 mx-auto p-3 py-md-5">
   <main>
      <h1>Task list for user: </h1>
      <p><a href="{% url 'tasktracker:add' %}">Add a new Task</a></p>
      <ul>
          {% for t in tasks %} 
          <li>
               <b>Task #{{t.id}}: {{t.title | safe}}</b>
               <b class="text-muted">(
                  {% if t.status == 'N' %}⚠️ Not started yet{% endif %}
                  {% if t.status == 'C' %}✅ Completed{% endif %}
                  {% if t.status == 'I' %}⏳ In Progress{% endif %}
                  )
               </b>
               <form action="/tasktracker/delete/{{t.id}}/" method = "post">
                  {% csrf_token %}
                  <input class="btn btn-danger" type="submit" value="Delete">
               </form> 
          </li>
          {% endfor %}
      </ul>
   </main>
</div>
{% endblock %}